<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <title><?=$v($title)?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="manifest" href="site.webmanifest">
    <link rel="apple-touch-icon" href="icon.png">
    <!-- Place favicon.ico in the root directory -->
    <style>
        <?php require_once "css/main.css"?>
    </style>

    <meta name="theme-color" content="#fafafa">
</head>
<body>
<!--[if IE]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
<![endif]-->
<ul class="top-bar__wrapper">
    <li><a></a></li>
    <li><a></a></li>
</ul>

<nav class="container" itemscope itemtype="http://schema.org/SiteNavigationElement">
    <div class="logo">
        <?= $logo;?>
    </div>

    <ul class="main__wrapper">
        <?php foreach($menu as $item):?>
            <li itemprop="name"><a itemprop="url" href="<?= $item['slug']?>"><?= $item['name']?></a></li>
        <?php endforeach;?>
    </ul>
</nav>
<?=$v->section('content')?>
</body>
</html>





